[package]
name = "sharding"
version = "0.1.0"
edition = "2021"
publish = false

[features]
testing = ["dep:rand"]

[dependencies]
thiserror = { workspace = true }
rand = { workspace = true, optional = true }

[dev-dependencies]
rand = { workspace = true }

[lints]
workspace = true

