[package]
name = "wcn_storage_api2"
version = "0.1.0"
edition = "2021"
publish = false

[lints]
workspace = true

[features]
default = []
rpc_client = ["wcn_rpc/client"]
rpc_server = ["wcn_rpc/server"]
testing = ["xxhash-rust", "serde_json"]

[dependencies]
wc = { workspace = true, features = ["future", "metrics"] }
auth = { workspace = true }
derive_more = { workspace = true, features = ["from", "try_into"] }
derive-where = { workspace = true }
strum = { workspace = true, features = ["derive"] }
tap = { workspace = true }

wcn_rpc = { workspace = true }
serde = "1"
thiserror = "1"
tracing = "0.1"
futures = "0.3"
time = "0.3"
const-hex = "1.14"

# testing
xxhash-rust = { workspace = true, optional = true }
serde_json = { version = "1", optional = true }

[dev-dependencies]
wcn_storage_api2 = { path = ".", features = ["rpc_client", "rpc_server"] }
tokio = { version = "1", default-features = false }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rand = "0.8"
