[package]
name = "wcn_storage_api2"
version = "0.1.0"
edition = "2021"
publish = false

[lints]
workspace = true

[features]
default = []
rpc_client = ["wcn_rpc/client"]
rpc_server = ["wcn_rpc/server"]
testing = ["xxhash-rust", "serde_json"]

[dependencies]
# Local
wcn_rpc = { workspace = true }

# Org
wc = { workspace = true, features = ["future", "metrics"] }

# Derives
derive_more = { workspace = true, features = ["from", "try_into"] }
derive-where = { workspace = true }
strum = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

# General purpose
tap = { workspace = true }
time = { workspace = true }

# Encoding
const-hex = { workspace = true }

# Serialization
serde = { workspace = true }
serde_json = { version = "1", optional = true }

# Async
futures = { workspace = true }

# O11y
tracing = { workspace = true }

# Other
xxhash-rust = { workspace = true, optional = true }

[dev-dependencies]
wcn_storage_api2 = { workspace = true, features = ["rpc_client", "rpc_server"] }

rand = { workspace = true }

tokio = { workspace = true }

tracing-subscriber = { workspace = true, features = ["fmt", "env-filter"] }
