[package]
name = "wcn_storage_api2"
version = "0.1.0"
edition = "2021"
publish = false

[lints]
workspace = true

[features]
default = ["rpc_client", "rpc_server"]
rpc_client = ["wcn_rpc/client"]
rpc_server = ["wcn_rpc/server"]

[dependencies]
wc = { workspace = true, features = ["future", "metrics"] }
auth = { workspace = true }
derive_more = { workspace = true, features = ["from", "try_into"] }
strum = { workspace = true , features = ["derive"] }

wcn_rpc = { workspace = true }
serde = "1"
thiserror = "1"
tracing = "0.1"
futures = "0.3"
time = "0.3"
const-hex = "1.14"
