[package]
name = "test_utils"
version = "0.1.0"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
relay_rpc = { workspace = true }
relay_storage = { workspace = true }
rocksdb = { version = "0.21", default-features = false, features = ["lz4"] }
futures-util = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
base64 = "0.20"
tempfile = "3"
bs58 = "0.4"
tracing = { version = "0.1", features = ["log"] }
cerberus = { workspace = true }

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "parking_lot",
] }
tracing-appender = "0.2"
test-log = "0.2"
env_logger = "0.10"
