tag_prefix = "v"

[commit_types]
tests = { changelog_title = "Tests" }

[changelog]
path        = "CHANGELOG.md"
template    = "remote"
remote      = "github.com"
owner       = "WalletConnect"
repository  = "irn-node"
