version: "3.9"
services:
  node1:
    container_name: irn-node-1
    image: irn:master
    pull_policy: build
    build:
      dockerfile: ./Dockerfile
      context: ./
      args:
        PROFILE: debug
    volumes:
      - irn-node-1:/irn
    ports:
      - 3001:3000
      - 3101:3001
      - 3201:3002
    env_file:
      - ./irn.common.env
    environment:
      - SECRET_KEY=00000000000000000000000000000001
      - PEER_12D3KooWKCjCtAy1myLoPbeUrVS6BBhzVHjLRHKvMS4gCoobyBbb=/dns4/node2/tcp/3000
      - PEER_12D3KooWMeFudZutoDEqKAsZ51HzyUELGsUUX5rmWSRwxMq3spYL=/dns4/node3/tcp/3000
      - PEER_12D3KooWSfyLo174Etqyr9a4VWhyfZG2wA8T6tB1MFDAZYhLanFz=/dns4/node4/tcp/3000
      - PEER_12D3KooWBgLHcVYcyUP7eDVDzJonXVhCEhDtkNAMrWrkdjQSSLic=/dns4/node5/tcp/3000
  node2:
    container_name: irn-node-2
    image: irn:master
    pull_policy: build
    build:
      dockerfile: ./Dockerfile
      context: ./
      args:
        PROFILE: debug
    volumes:
      - irn-node-2:/irn
    ports:
      - 3002:3000
      - 3102:3001
      - 3202:3002
    env_file:
      - ./irn.common.env
    environment:
      - SECRET_KEY=00000000000000000000000000000002
      - PEER_12D3KooWBnTyEyBVeYpZJobw78rb85nNamrYQR3Tc6gJmfQ76pG4=/dns4/node1/tcp/3000
      - PEER_12D3KooWMeFudZutoDEqKAsZ51HzyUELGsUUX5rmWSRwxMq3spYL=/dns4/node3/tcp/3000
      - PEER_12D3KooWSfyLo174Etqyr9a4VWhyfZG2wA8T6tB1MFDAZYhLanFz=/dns4/node4/tcp/3000
      - PEER_12D3KooWBgLHcVYcyUP7eDVDzJonXVhCEhDtkNAMrWrkdjQSSLic=/dns4/node5/tcp/3000
  node3:
    container_name: irn-node-3
    image: irn:master
    pull_policy: build
    build:
      dockerfile: ./Dockerfile
      context: ./
      args:
        PROFILE: debug
    volumes:
      - irn-node-3:/irn
    ports:
      - 3003:3000
      - 3103:3001
      - 3203:3002
    env_file:
      - ./irn.common.env
    environment:
      - SECRET_KEY=00000000000000000000000000000003
      - PEER_12D3KooWBnTyEyBVeYpZJobw78rb85nNamrYQR3Tc6gJmfQ76pG4=/dns4/node1/tcp/3000
      - PEER_12D3KooWKCjCtAy1myLoPbeUrVS6BBhzVHjLRHKvMS4gCoobyBbb=/dns4/node2/tcp/3000
      - PEER_12D3KooWSfyLo174Etqyr9a4VWhyfZG2wA8T6tB1MFDAZYhLanFz=/dns4/node4/tcp/3000
      - PEER_12D3KooWBgLHcVYcyUP7eDVDzJonXVhCEhDtkNAMrWrkdjQSSLic=/dns4/node5/tcp/3000
  node4:
    container_name: irn-node-4
    image: irn:master
    pull_policy: build
    build:
      dockerfile: ./Dockerfile
      context: ./
      args:
        PROFILE: debug
    volumes:
      - irn-node-4:/irn
    ports:
      - 3004:3000
      - 3104:3001
      - 3204:3002
    env_file:
      - ./irn.common.env
    environment:
      - SECRET_KEY=00000000000000000000000000000004
      - PEER_12D3KooWBnTyEyBVeYpZJobw78rb85nNamrYQR3Tc6gJmfQ76pG4=/dns4/node1/tcp/3000
      - PEER_12D3KooWKCjCtAy1myLoPbeUrVS6BBhzVHjLRHKvMS4gCoobyBbb=/dns4/node2/tcp/3000
      - PEER_12D3KooWMeFudZutoDEqKAsZ51HzyUELGsUUX5rmWSRwxMq3spYL=/dns4/node3/tcp/3000
      - PEER_12D3KooWBgLHcVYcyUP7eDVDzJonXVhCEhDtkNAMrWrkdjQSSLic=/dns4/node5/tcp/3000
  node5:
    container_name: irn-node-5
    image: irn:master
    pull_policy: build
    build:
      dockerfile: ./Dockerfile
      context: ./
      args:
        PROFILE: debug
    volumes:
      - irn-node-5:/irn
    ports:
      - 3005:3000
      - 3105:3001
      - 3205:3002
    env_file:
      - ./irn.common.env
    environment:
      - SECRET_KEY=00000000000000000000000000000005
      - PEER_12D3KooWBnTyEyBVeYpZJobw78rb85nNamrYQR3Tc6gJmfQ76pG4=/dns4/node1/tcp/3000
      - PEER_12D3KooWKCjCtAy1myLoPbeUrVS6BBhzVHjLRHKvMS4gCoobyBbb=/dns4/node2/tcp/3000
      - PEER_12D3KooWMeFudZutoDEqKAsZ51HzyUELGsUUX5rmWSRwxMq3spYL=/dns4/node3/tcp/3000
      - PEER_12D3KooWSfyLo174Etqyr9a4VWhyfZG2wA8T6tB1MFDAZYhLanFz=/dns4/node4/tcp/3000
volumes:
  irn-node-1:
  irn-node-2:
  irn-node-3:
  irn-node-4:
  irn-node-5:
