version: "3.9"

services:
  anvil-node-1:
    image: ghcr.io/foundry-rs/foundry
    platform: linux/x86_64
    profiles:
      - oracle
    command: anvil
    container_name: anvil-node-1
    environment:
      - ANVIL_IP_ADDR=0.0.0.0
      - CHAIN_ID=31337
      - MNEMONIC="test test test test test test test test test test test junk"
      - API_KEY_OPTIMISTIC_ETHERSCAN="PLACEHOLDER"
      - API_KEY_ETHERSCAN="PLACEHOLDER"
      - REWARDS_PER_EPOCH=1000000000000000000000
      - INITIAL_TREASURY_BALANCE=365000000000000000000000
      - MAX_NODES=50
      - MIN_STAKE_AMOUNT=100000000000000000000000
    networks:
      relay:
        ipv4_address: 172.11.0.105
    ports:
      - 8545:8545

  irn-node-1:
    image: irn:master
    build:
      dockerfile: ./Dockerfile
      context: ./
      args:
        - PROFILE=debug
    container_name: irn-node-1
    networks:
      relay:
        ipv4_address: 172.11.0.101
    ports:
      - "3010:3010/udp"
      - "3011:3011/udp"
      - 3012:3012
    environment:
      - ADDR=/ip4/172.11.0.101/udp/3010/quic-v1
      - API_ADDR=/ip4/172.11.0.101/udp/3011/quic-v1
      - METRICS_ADDR=172.11.0.101:3012
      - BOOTSTRAP_NODES=12D3KooWE5w9ksamQEejyYn2sY2MixqCn4RYQ8Cfy3Ad3MRiBjHs_3,12D3KooWDJrGKPuU1vJLBZv2UXfcZvdBprUgAkjvkUET7q2PzwPp_1,12D3KooWE79egFys7LW8NyUDicrnxUBnABXqXKU9PK9HF4xaBCuY_2
      - RAFT_DIR=/irn/raft
      - ROCKSDB_DIR=/irn/rocksdb
      - REPLICATION_STRATEGY_FACTOR=3
      - REPLICATION_STRATEGY_LEVEL=Quorum
      - LOG_LEVEL=info,tarpc=error
      - GROUP=1
      - SECRET_KEY=Kz5phRjzWE5yPAs5JagXtNTAjGOy/JhWl+t+SRtU+Lc=
      - PEER_12D3KooWE79egFys7LW8NyUDicrnxUBnABXqXKU9PK9HF4xaBCuY_2=/ip4/172.11.0.102/udp/3020/quic-v1
      - PEER_12D3KooWE5w9ksamQEejyYn2sY2MixqCn4RYQ8Cfy3Ad3MRiBjHs_3=/ip4/172.11.0.103/udp/3030/quic-v1

  irn-node-2:
    image: irn:master
    container_name: irn-node-2
    networks:
      relay:
        ipv4_address: 172.11.0.102
    ports:
      - "3020:3020/udp"
      - "3021:3021/udp"
      - 3022:3022
    environment:
      - ADDR=/ip4/172.11.0.102/udp/3020/quic-v1
      - API_ADDR=/ip4/172.11.0.102/udp/3021/quic-v1
      - METRICS_ADDR=172.11.0.102:3022
      - BOOTSTRAP_NODES=12D3KooWE5w9ksamQEejyYn2sY2MixqCn4RYQ8Cfy3Ad3MRiBjHs_3,12D3KooWDJrGKPuU1vJLBZv2UXfcZvdBprUgAkjvkUET7q2PzwPp_1,12D3KooWE79egFys7LW8NyUDicrnxUBnABXqXKU9PK9HF4xaBCuY_2
      - RAFT_DIR=/irn/raft
      - ROCKSDB_DIR=/irn/rocksdb
      - REPLICATION_STRATEGY_FACTOR=3
      - REPLICATION_STRATEGY_LEVEL=Quorum
      - LOG_LEVEL=info,tarpc=error
      - GROUP=2
      - SECRET_KEY=aAz8/3kOkdukRmWks9/QCgiKBAm+3FnqxXE35U44t/c=
      - PEER_12D3KooWDJrGKPuU1vJLBZv2UXfcZvdBprUgAkjvkUET7q2PzwPp_1=/ip4/172.11.0.101/udp/3010/quic-v1
      - PEER_12D3KooWE5w9ksamQEejyYn2sY2MixqCn4RYQ8Cfy3Ad3MRiBjHs_3=/ip4/172.11.0.103/udp/3030/quic-v1
      - ETH_ADDRESS=0x70997970c51812dc3a010c7d01b50e0d17dc79c8

  irn-node-3:
    image: irn:master
    container_name: irn-node-3
    networks:
      relay:
        ipv4_address: 172.11.0.103
    ports:
      - "3030:3030/udp"
      - "3031:3031/udp"
      - 3032:3032
    environment:
      - ADDR=/ip4/172.11.0.103/udp/3030/quic-v1
      - API_ADDR=/ip4/172.11.0.103/udp/3031/quic-v1
      - METRICS_ADDR=172.11.0.103:3032
      - BOOTSTRAP_NODES=12D3KooWE5w9ksamQEejyYn2sY2MixqCn4RYQ8Cfy3Ad3MRiBjHs_3,12D3KooWDJrGKPuU1vJLBZv2UXfcZvdBprUgAkjvkUET7q2PzwPp_1,12D3KooWE79egFys7LW8NyUDicrnxUBnABXqXKU9PK9HF4xaBCuY_2
      - RAFT_DIR=/irn/raft
      - ROCKSDB_DIR=/irn/rocksdb
      - REPLICATION_STRATEGY_FACTOR=3
      - REPLICATION_STRATEGY_LEVEL=Quorum
      - LOG_LEVEL=info,tarpc=error
      - GROUP=3
      - SECRET_KEY=Fn+92TJONBeB3ji6jd083wfPiRuZF5ScPSyhfCJy8C0=
      - PEER_12D3KooWDJrGKPuU1vJLBZv2UXfcZvdBprUgAkjvkUET7q2PzwPp_1=/ip4/172.11.0.101/udp/3010/quic-v1
      - PEER_12D3KooWE79egFys7LW8NyUDicrnxUBnABXqXKU9PK9HF4xaBCuY_2=/ip4/172.11.0.102/udp/3020/quic-v1
      - ETH_ADDRESS=0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc

networks:
  relay:
    ipam:
      config:
        - subnet: 172.11.0.0/16
