version: "3.9"

services:
  irn-node-1:
    image: irn:master
    build:
      dockerfile: ./Dockerfile
      context: ./
      args:
        - PROFILE=debug
    container_name: irn-node-1
    networks:
      relay:
        ipv4_address: 
    ports:
      - "3010:3010/udp"
      - "3011:3011/udp"
      - 3012:3012
    environment:
      - ADDR=/ip4//udp/3010/quic-v1
      - API_ADDR=/ip4//udp/3011/quic-v1
      - METRICS_ADDR=:3012
      - BOOTSTRAP_NODES=12D3KooWE5w9ksamQEejyYn2sY2MixqCn4RYQ8Cfy3Ad3MRiBjHs_3,12D3KooWDJrGKPuU1vJLBZv2UXfcZvdBprUgAkjvkUET7q2PzwPp_1,12D3KooWE79egFys7LW8NyUDicrnxUBnABXqXKU9PK9HF4xaBCuY_2
      - RAFT_DIR=/irn/raft
      - ROCKSDB_DIR=/irn/rocksdb
      - REPLICATION_STRATEGY_FACTOR=3
      - REPLICATION_STRATEGY_LEVEL=Quorum
      - LOG_LEVEL=info,tarpc=error
      - GROUP=1
      - SECRET_KEY=Kz5phRjzWE5yPAs5JagXtNTAjGOy/JhWl+t+SRtU+Lc=
      - PEER_12D3KooWE79egFys7LW8NyUDicrnxUBnABXqXKU9PK9HF4xaBCuY_2=/ip4//udp/3020/quic-v1
      - PEER_12D3KooWE5w9ksamQEejyYn2sY2MixqCn4RYQ8Cfy3Ad3MRiBjHs_3=/ip4//udp/3030/quic-v1

  irn-node-2:
    image: irn:master
    container_name: irn-node-2
    networks:
      relay:
        ipv4_address: 
    ports:
      - "3020:3020/udp"
      - "3021:3021/udp"
      - 3022:3022
    environment:
      - ADDR=/ip4//udp/3020/quic-v1
      - API_ADDR=/ip4//udp/3021/quic-v1
      - METRICS_ADDR=:3022
      - BOOTSTRAP_NODES=12D3KooWE5w9ksamQEejyYn2sY2MixqCn4RYQ8Cfy3Ad3MRiBjHs_3,12D3KooWDJrGKPuU1vJLBZv2UXfcZvdBprUgAkjvkUET7q2PzwPp_1,12D3KooWE79egFys7LW8NyUDicrnxUBnABXqXKU9PK9HF4xaBCuY_2
      - RAFT_DIR=/irn/raft
      - ROCKSDB_DIR=/irn/rocksdb
      - REPLICATION_STRATEGY_FACTOR=3
      - REPLICATION_STRATEGY_LEVEL=Quorum
      - LOG_LEVEL=info,tarpc=error
      - GROUP=2
      - SECRET_KEY=aAz8/3kOkdukRmWks9/QCgiKBAm+3FnqxXE35U44t/c=
      - PEER_12D3KooWDJrGKPuU1vJLBZv2UXfcZvdBprUgAkjvkUET7q2PzwPp_1=/ip4//udp/3010/quic-v1
      - PEER_12D3KooWE5w9ksamQEejyYn2sY2MixqCn4RYQ8Cfy3Ad3MRiBjHs_3=/ip4//udp/3030/quic-v1

  irn-node-3:
    image: irn:master
    container_name: irn-node-3
    networks:
      relay:
        ipv4_address: 
    ports:
      - "3030:3030/udp"
      - "3031:3031/udp"
      - 3032:3032
    environment:
      - ADDR=/ip4//udp/3030/quic-v1
      - API_ADDR=/ip4//udp/3031/quic-v1
      - METRICS_ADDR=:3032
      - BOOTSTRAP_NODES=12D3KooWE5w9ksamQEejyYn2sY2MixqCn4RYQ8Cfy3Ad3MRiBjHs_3,12D3KooWDJrGKPuU1vJLBZv2UXfcZvdBprUgAkjvkUET7q2PzwPp_1,12D3KooWE79egFys7LW8NyUDicrnxUBnABXqXKU9PK9HF4xaBCuY_2
      - RAFT_DIR=/irn/raft
      - ROCKSDB_DIR=/irn/rocksdb
      - REPLICATION_STRATEGY_FACTOR=3
      - REPLICATION_STRATEGY_LEVEL=Quorum
      - LOG_LEVEL=info,tarpc=error
      - GROUP=3
      - SECRET_KEY=Fn+92TJONBeB3ji6jd083wfPiRuZF5ScPSyhfCJy8C0=
      - PEER_12D3KooWDJrGKPuU1vJLBZv2UXfcZvdBprUgAkjvkUET7q2PzwPp_1=/ip4//udp/3010/quic-v1
      - PEER_12D3KooWE79egFys7LW8NyUDicrnxUBnABXqXKU9PK9HF4xaBCuY_2=/ip4//udp/3020/quic-v1

networks:
  relay:
    ipam:
      config:
        - subnet: /16
