[package]
name = "irn_storage"
version = "0.1.0"
edition = "2021"
description = "Storage related traits and objects"
publish = false

[dependencies]
relay_rpc = { git = "https://github.com/WalletConnect/WalletConnectRust.git", tag = "v0.29.1" }
relay_client = { git = "https://github.com/WalletConnect/WalletConnectRust.git", tag = "v0.29.1" }
wc = { git = "https://github.com/WalletConnect/utils-rs.git", tag = "v0.8.0", default-features = false, features = [
    "metrics",
] }

thiserror = "1.0"
async-trait = "0.1"
rmp-serde = "=1.1.2"
serde = { version = "1", features = ["derive"] }
wither = { git = "https://github.com/WalletConnect/wither.git", rev = "102b80e", features = [
    "bson-chrono-0_4",
] }
futures-util = { version = "0.3", default-features = false, features = [
    "sink",
    "std",
] }
chrono = { version = "0.4", features = ["serde"] }
bitflags = { version = "2.3", default-features = false, features = ["serde"] }
data-encoding = "2.3"

[dependencies.xxhash-rust]
version = "0.8.6"
features = ["xxh3", "const_xxh3"]

[dev-dependencies]
serde_json = "1.0"

[lints.clippy]
all = { level = "deny", priority = -1 }
style = { level = "warn", priority = -1 }
absolute_paths = "warn"
bool_to_int_with_if = "warn"
clear_with_drain = "warn"
cloned_instead_of_copied = "warn"
collection_is_never_read = "warn"
empty_structs_with_brackets = "warn"
explicit_into_iter_loop = "warn"
filter_map_next = "warn"
implicit_clone = "warn"
implied_bounds_in_impls = "warn"
inconsistent_struct_constructor = "warn"
inefficient_to_string = "warn"
into_iter_without_iter = "warn"
iter_not_returning_iterator = "warn"
iter_with_drain = "warn"
manual_assert = "warn"
manual_instant_elapsed = "warn"
manual_string_new = "warn"
match_bool = "warn"
mem_forget = "warn"
mismatching_type_param_order = "warn"
needless_continue = "warn"
needless_for_each = "warn"
needless_pass_by_ref_mut = "warn"
print_stdout = "warn"
readonly_write_lock = "warn"
redundant_clone = "warn"
redundant_type_annotations = "warn"
rest_pat_in_fully_bound_structs = "warn"
same_functions_in_if_condition = "warn"
struct_excessive_bools = "warn"
trait_duplication_in_bounds = "warn"
type_repetition_in_bounds = "warn"
unnecessary_box_returns = "warn"
unnecessary_self_imports = "warn"
unused_peekable = "warn"
useless_let_if_seq = "warn"
