[package]
name = "wcn_client"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
# Local
wcn_cluster = { workspace = true, default-features = false }
wcn_cluster_api = { workspace = true, features = ["rpc_client"] }
wcn_rpc = { workspace = true, features = ["client"] }
wcn_storage_api = { workspace = true, features = ["rpc_client"] }

# Org
wc = { workspace = true, features = ["metrics"] }

# Dervies
derive_more = { workspace = true }
derive-where = { workspace = true }
thiserror = { workspace = true }

# General purpose
arc-swap = { workspace = true }
tap = { workspace = true }
rand = { workspace = true }
strum = { workspace = true }

# Async
futures = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
futures-concurrency = { workspace = true }
tokio-util = { workspace = true }
tokio-stream = { workspace = true, features = ["time"] }

# O11y
tracing = { workspace = true }

# Crypto
ring = "0.17"

# Other
libp2p-identity = { workspace = true }
phi-accrual-failure-detector = "0.1"

[lints]
workspace = true
