# TODO: Describe parameters.

known_peers = []
bootstrap_nodes = []

# [identity]
# private_key = "yDt4KicJ5aJF8nS4zYtDPrel2WJcU6cD7hO+u5m5Arg="
# region = "eu"
# organization = "WalletConnect"
# eth_address = "0xeD380b8da6012c20856CEc076C348AC44fA50f63"
# network_id = "irn_mainnet"

[server]
bind_address = "0.0.0.0"
server_port = 3010
client_port = 3011
metrics_port = 3012
auth_port = 3013
admin_port = 3014
warmup_delay = 45000

# [[known_peers]]
# id = "12D3KooWBHED7RfVicYMAkfypqcAX8rtQmirfKh91JJCUDTroPF9"
# address = "127.0.0.1:3010"

# [[bootstrap_nodes]]
# id = "12D3KooWBHED7RfVicYMAkfypqcAX8rtQmirfKh91JJCUDTroPF9"
# group = 1

[authorization]
enable = true
is_consensus_member = false
clients = []
consensus_candidates = []

[storage]
data_dir = "./data"
consensus_dir = "./consensus"

# [storage.rocksdb]
# ratelimiter = 67108864

# The following values are configured for a machine with 16GB of RAM.
# write_buffer_size = 134217728
# max_write_buffer_number = 8
# min_write_buffer_number_to_merge = 2
# block_cache_size = 4294967296
# block_size = 4096
# row_cache_size = 1073741824

# The following values are automatically configured based on the number of cores.
# num_batch_threads = 8
# num_callback_threads = 32
# max_subcompactions = 8
# max_background_jobs = 32
# increase_parallelism = 16

[replication]
consistency_level = "Quorum"
factor = 3

[network]
request_concurrency_limit = 4500
request_limiter_queue = 65536
connection_timeout = 1000
request_timeout = 5000
replication_request_timeout = 2000

# [smart_contract]
# eth_rpc_url = ""
# config_address = ""
