[package]
name = "irn_client_api"
version = "0.1.0"
edition = "2021"
publish = false

[lints]
workspace = true

[features]
client = ["irn_rpc/client"]
server = ["irn_rpc/server"]

[dependencies]
irn_rpc = { workspace = true }
api = { workspace = true }
irn_core = { package = "irn_core", path = "../core" }
sharding = { path = "../sharding" }
serde = "1"
thiserror = "1"
tracing = "0.1"
chrono = { version = "0.4", default-features = false, features = ["now"] }
data-encoding = "2.6"
serde_json = "1.0"
async-stream = "0.3"
futures-util = "0.3"
tokio = { version = "1", features = ["sync"] }
xxhash-rust = { version = "0.8", features = ["xxh3", "const_xxh3"] }
postcard = { version = "1.0", default-features = false, features = [
    "alloc",
    "use-std",
] }
arc-swap = "1.7"
