extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  resourcedetection:
    detectors:
      - env
      - system
      - ecs
  resource:
    attributes:
      - key: os.type
        action: delete
      - key: host.name
        action: delete
  attributes:
    actions:
      - key: otel.library.name
        action: delete
      - key: otel.library.version
        action: delete
      - key: span.kind
        action: delete
      - key: internal.span.format
        action: delete
      - key: thread.id
        action: delete
      - key: thread.name
        action: delete
      - key: code.namespace
        action: delete
      - key: code.filepath
        action: delete
      - key: code.lineno
        action: delete
      - key: enduser.id
        from_attribute: request_client_id
        action: upsert
  batch/traces:
    timeout: 3s
    send_batch_size: 50

exporters:
  awsxray:
    index_all_attributes: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection, resource, attributes, batch/traces]
      exporters: [awsxray]

  extensions: [health_check]
