[package]
name = "wcn_logging"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
tracing = { workspace = true }
tracing-appender = "0.2"
tracing-subscriber = { workspace = true, features = [
    "env-filter",
    "parking_lot",
    "json",
] }

[lints]
workspace = true
