[package]
name = "wcn_rpc"
version = "0.1.0"
edition = "2021"
publish = false

[lints]
workspace = true

[features]
client = []
server = []

[dependencies]
# Local
wcn_rpc_derive = { path = "./derive" }

# Org
wc = { workspace = true, features = ["collections", "future", "metrics"] }

# Derives
derive_more = { workspace = true, features = ["display", "try_from", "deref", "from"] }
derive-where = { workspace = true }
thiserror = { workspace = true }
strum = { workspace = true , features = ["derive"] }

# General purpose
tap = { workspace = true }
tracing = { workspace = true }
bytes = { workspace = true }
pin-project = { workspace = true }
rand = { workspace = true, features = ["small_rng"] }

# Async
futures = { workspace = true }
futures-concurrency = { workspace = true }
futures-util = { version = "0.3" }
futures-timer = { version = "3.0" }
tokio = { workspace = true, features = ["io-util"] }
tokio-util = { version = "0.7", features = ["compat", "codec"] }
tokio-serde = { workspace = true, features = ["json"] }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }
postcard = { workspace = true, features = ["alloc"] }

# Other
libp2p-identity = { workspace = true, default-features = false }
libp2p-tls = { version = "0.6", default-features = false }
quinn = { version = "0.11.8", default-features = false, features = ["rustls", "runtime-tokio"] }
quinn-proto = { version = "0.11", default-features = false }
socket2 = { version = "0.6.0", default-features = false }
nix = { version = "0.30", default-features = false, features = ["socket", "net"] }
governor = { version = "0.10", default-features = false, features = ["std"] }
mini-moka = { version = "0.10", default-features = false, features = ["sync"] }

[dev-dependencies]
