[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
via_ir = true

remappings = ["openzeppelin-contracts/=./dependencies/@openzeppelin-contracts-5.3.0/"]

[dependencies]
forge-std = "1.9.7"
"@openzeppelin-contracts" = "5.3.0"
solady = "0.1.19"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
