[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
via_ir = true
solc = "0.8.26"                   # Pin specific version for reproducibility
optimizer = true
optimizer_runs = 200
fuzz = { runs = 256 }              # Cleaner inline syntax
invariant = { runs = 10, depth = 15, fail_on_revert = true, show_metrics = true }
gas_reports = ["*"]               # Generate gas reports for all contracts
script = "script"
test = "tests"


[profile.thorough]
fuzz = { runs = 1000 }
invariant = { runs = 100, depth = 50, fail_on_revert = true, show_metrics = true }
verbosity = 2                     # More detailed output for thorough testing

# Basic formatting rules
[fmt]
line_length = 120
quote_style = "double"
tab_width = 4

[dependencies]
forge-std = "1.9.7"
"@openzeppelin-contracts" = "5.3.0"
solady = "0.1.19"
"@openzeppelin-contracts-upgradeable" = "5.3.0"
openzeppelin-foundry-upgrades = "0.4.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
