version: "3.9"
services:
  rs-relay-test:
    build:
      dockerfile: ./ops/Dockerfile-test
      context: ../relay
    volumes:
      - rs-relay-test-data-target:/rs-relay/target
      - rs-relay-test-data-cargo-cache:/root/.cargo
      - rs-relay-test-data-cargo-registry:/usr/local/cargo/registry
    networks:
      walletconnect-rs-relay:
        ipv4_address: 
    depends_on:
      rs-relay-srv0:
        condition: service_started
      rs-relay-srv1:
        condition: service_started
      activemq:
        condition: service_started
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - RELAY_BIND_IP=
      - RELAY_EXTERNAL_IP=
      - RELAY_STORAGE_UNADDRESSED_MAILBOX_REDIS_ADDR_READ=redis://redis:6379/0
      - RELAY_STORAGE_ADDRESSED_MAILBOX_REDIS_ADDR_READ=redis://redis:6379/0
      - RELAY_STORAGE_NOTIFICATIONS_REDIS_ADDR_READ=redis://redis:6379/0
      - RELAY_STORAGE_ROUTING_TABLE_REDIS_ADDR_READ=redis://redis:6379/0
      - RELAY_STORAGE_UNADDRESSED_MAILBOX_REDIS_ADDR_WRITE=redis://redis:6379/0
      - RELAY_STORAGE_ADDRESSED_MAILBOX_REDIS_ADDR_WRITE=redis://redis:6379/0
      - RELAY_STORAGE_NOTIFICATIONS_REDIS_ADDR_WRITE=redis://redis:6379/0
      - RELAY_STORAGE_ROUTING_TABLE_REDIS_ADDR_WRITE=redis://redis:6379/0
      - RELAY_STORAGE_PROJECT_DATA_REDIS_ADDR_WRITE=redis://redis:6379/0
      - RELAY_STORAGE_PROJECT_DATA_REDIS_ADDR_READ=redis://redis:6379/0
      - RELAY_STORAGE_PERSISTENT_MAILBOX_MONGO_ADDR=mongodb://admin:admin@mongo:27017/relay?authSource=admin
      - RELAY_STORAGE_WEBHOOK_AMQP_ADDR_PRIMARY=amqp://admin:admin@activemq:5672
      - RELAY_STORAGE_WEBHOOK_AMQP_ADDR_SECONDARY=amqp://admin:admin@activemq:5672
      - RUST_BACKTRACE=1
    # Run all integration tests, including the ones that depend on the storage (redis, mongo, activemq).
    command: ["cargo", "test", "--all-features"]
volumes:
  rs-relay-test-data-target:
  rs-relay-test-data-cargo-cache:
  rs-relay-test-data-cargo-registry:
